# Generated by Django 4.1.7 on 2023-02-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_category_product_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['time_create', 'name'], 'verbose_name': 'Продуктілер', 'verbose_name_plural': 'Продуктілер'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, verbose_name='Бренд аты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='honey.category', verbose_name='Категориясы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, verbose_name='Сипаттамасы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикациясы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Сурет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Өзгертілген уақыт'),
        ),
    ]
